// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkIWPL4-BgQ3EA6arC74a-e6_s5runix4',
    appId: '1:389398616787:web:9f4f3afc1763e9a14d9226',
    messagingSenderId: '389398616787',
    projectId: 'messagefinal-app',
    authDomain: 'messagefinal-app.firebaseapp.com',
    storageBucket: 'messagefinal-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCtnN8qIi0E7lsdMqKTYorv03MTu0JXa0',
    appId: '1:389398616787:android:4bb80da4975f2fe64d9226',
    messagingSenderId: '389398616787',
    projectId: 'messagefinal-app',
    storageBucket: 'messagefinal-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCulAqnixH1m5aWhgtyi2huTUpE7X_VYNY',
    appId: '1:389398616787:ios:adadfd1e09c275ee4d9226',
    messagingSenderId: '389398616787',
    projectId: 'messagefinal-app',
    storageBucket: 'messagefinal-app.appspot.com',
    iosBundleId: 'com.example.messagefinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCulAqnixH1m5aWhgtyi2huTUpE7X_VYNY',
    appId: '1:389398616787:ios:e5cf1be671365dcb4d9226',
    messagingSenderId: '389398616787',
    projectId: 'messagefinal-app',
    storageBucket: 'messagefinal-app.appspot.com',
    iosBundleId: 'com.example.messagefinal.RunnerTests',
  );
}
